const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const files=['browser','android','desktop','bridge'];
function create(window={}){
 const c=vm.createContext({window,URL,TextEncoder,TextDecoder,Uint8Array,Blob,btoa,atob,setTimeout,clearTimeout,AbortController,document:{addEventListener(){}},location:{href:'https://app.test/index.html',origin:'https://app.test'},console});
 for(const name of files){vm.runInContext(fs.readFileSync('platform/'+name+'.js','utf8'),c);Object.assign(c,c.window)}
 vm.runInContext(fs.readFileSync('web/secure-credentials.js','utf8'),c);c.SecureCredentials=c.window.SecureCredentials;return c;
}
(async()=>{
 const browser=create();assert.equal(browser.Platform.kind,'browser');const S=browser.SecureCredentials;assert.equal(S.protect('ocr-p','bearer','https://model.test/chat','','test-key'),S.TOKEN);assert.equal((await S.requestHeaders('ocr-p',S.TOKEN,'bearer','','https://model.test/chat')).Authorization,'Bearer test-key');assert.throws(()=>S.headers('ocr-p',S.TOKEN,'bearer','','https://other.test/chat'));assert.equal(create().SecureCredentials.has('ocr-p'),false,'browser secrets never persist between sessions');
 const calls=[],vault=new Map();let android;
 const native={httpRequest(id,method,url,headers,body){calls.push({id,method,url,headers,body});queueMicrotask(()=>android.window.__nativeHttpDone(id,200,'model reply'))},httpFetch(id,method,url,headers,mode,text){calls.push({id,method,url,headers,mode,text});queueMicrotask(()=>android.window.__nativeFetchDone(id,200,'{}',''))},uploadChunk(id,data){calls.push({id,data});return true},releaseTransfer(id){calls.push({release:id})},saveTransfer(id,name,mime){calls.push({save:id,name,mime})},copyText(text){calls.push({copy:text})},readClipboard:()=> 'clipboard',printScore(){},setImmersive(){},storeCredential(id,kind,url,user,secret){vault.set(id,{kind,url,user,secret});return true},hasCredential:id=>vault.has(id),deleteCredential:id=>(vault.delete(id),true)};
 android=create({AndroidTools:native});assert.equal(android.Platform.kind,'android');android.fetch=async()=>({blob:async()=>new Blob(['download'])});
 const model=await android.Platform.request('POST','https://model.test/chat',{}, {text:'prompt'},{model:true});assert.equal(await model.text(),'model reply');
 const file=await android.Platform.request('GET','https://dav.test/root/');assert.equal(await file.text(),'download');assert.ok(calls.some(c=>c.release));await android.Platform.saveBlob(new Blob(['saved']),'backup.zip','application/zip');assert.ok(calls.some(c=>c.save&&c.name==='backup.zip'));await android.Platform.copyText('abc');assert.equal(await android.Platform.readClipboard(),'clipboard');
 const commands=[],stored=new Map(),disk=new Map();
 const desktop=create({__TAURI_INTERNALS__:{async invoke(cmd,args){commands.push({cmd,args});if(cmd==='credential_list')return [];if(cmd==='credential_store'){const old=stored.get(args.id);if(args.secret===S.TOKEN){if(!old||old.url!==args.url||old.user!==args.user)throw Error('binding mismatch');return old}const meta={id:args.id,kind:args.kind,url:args.url,user:args.user};stored.set(args.id,meta);return meta}if(cmd==='credential_remove'){stored.delete(args.id);return}if(cmd==='http_request')return {status:200,headers:{},body:btoa(JSON.stringify({choices:[{message:{content:'OK'}}]}))};if(cmd==='save_file')return true;if(cmd==='read_clipboard')return 'desktop clipboard'}}});
 desktop.localStorage={getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,v)};for(const f of ['score-ocr','library']){vm.runInContext(fs.readFileSync('web/'+f+'.js','utf8'),desktop);Object.assign(desktop,desktop.window)}
 assert.equal(desktop.Platform.kind,'desktop');const cfg={mode:'llm',active:'p',profiles:[{id:'p',name:'test',baseUrl:'https://model.test',model:'vision',apiKey:'desktop-test-key'}]};assert.equal(await desktop.ScoreOCR.saveConfigAsync(cfg),true);assert.ok(!disk.get('flute.scoreOcr.v1').includes('desktop-test-key'));assert.equal(await desktop.ScoreOCR.testConnection(desktop.ScoreOCR.loadConfig()),'OK');const request=commands.find(c=>c.cmd==='http_request');assert.equal(request.args.headers['X-Flute-Credential'],'ocr-p');assert.ok(!JSON.stringify(request).includes('desktop-test-key'));
 const changed={...cfg,profiles:[{...cfg.profiles[0],baseUrl:'https://other.test',apiKey:S.TOKEN}]};assert.equal(await desktop.ScoreOCR.saveConfigAsync(changed),false);assert.equal(desktop.ScoreOCR.loadConfig().baseUrl,'https://model.test');
 assert.equal(await desktop.ScoreLibrary.saveDavConfigAsync({url:'https://dav.test/root/',user:'test',pass:'desktop-test-pass',folder:'scores'}),true);assert.ok(!disk.get('flute.webdav.v1').includes('desktop-test-pass'));await desktop.SecureCredentials.removeAsync('webdav');assert.equal(stored.has('webdav'),false);
 await desktop.Platform.saveBlob(new Blob(['bytes']),'score.txt');assert.ok(commands.some(c=>c.cmd==='save_file'&&c.args.data===btoa('bytes')));assert.equal(await desktop.Platform.readClipboard(),'desktop clipboard');
 console.log('PASS: browser session-only credentials, Android callbacks/binary transfer/save, desktop asynchronous secure-save/header references/address binding/forget/file/clipboard adapters.');
})().catch(e=>{console.error(e);process.exitCode=1});
// Modified by AI on 2026-10-08 10:06:28
