// Compile only DSP models. libfaust, its filesystem and editor never enter the App.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {instantiateFaustModuleFromFile,LibFaust,FaustCompiler,FaustMonoDspGenerator} from '@grame/faustwasm/dist/esm/index.js';
import {mark} from './build.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const compilerPath=path.join(root,'node_modules/@grame/faustwasm/libfaust-wasm/libfaust-wasm.js');
const module=await instantiateFaustModuleFromFile(compilerPath);
const lib=new LibFaust(module),compiler=new FaustCompiler(lib),models={};
const controls=items=>items.flatMap(i=>i.items?controls(i.items):i.index!=null?[{label:i.label,index:i.index,init:i.init??0}]:[]);
for(const id of ['flute','bowed','hammer','piano','guzheng','clarinet']){
 const source=fs.readFileSync(path.join(root,'web/vendor/faust/source',id+'.dsp'),'utf8');
 const generator=await new FaustMonoDspGenerator().compile(compiler,id,source,'-I /usr/share/faust -ftz 2');
 if(!generator)throw Error(compiler.getErrorMessage());
 const factory=generator.factory,meta=JSON.parse(factory.json);
 if(meta.inputs!==0||meta.outputs!==1||meta.ui.some(i=>i.type==='soundfile'))throw Error('Models must be self-contained mono generators');
 models[id]={size:meta.size,controls:controls(meta.ui),code:Buffer.from(factory.code).toString('base64'),sourceSha256:crypto.createHash('sha256').update(source).digest('hex'),wasmBytes:factory.code.length};
 console.log(`${id}: ${factory.code.length} bytes WASM, ${meta.size} bytes DSP state`);
}
const digest=crypto.createHash('sha256').update(JSON.stringify(models)).digest('hex');
const bank={digest,compiler:lib.version(),package:'@grame/faustwasm@0.19.0',models};
const out=mark("'use strict';\n// Generated by npm run build:faust. Sources and licenses are beside this file.\nwindow.FaustBank="+JSON.stringify(bank)+';','.js');
fs.writeFileSync(path.join(root,'web/vendor/faust/models.js'),out);
if(Buffer.byteLength(out)>128*1024)throw Error('Faust bank exceeds the 128 KiB budget');
console.log(`Packaged bank: ${Buffer.byteLength(out)} bytes. No compiler/runtime SDK or recordings packaged.`);
// Modified by AI on 2026-10-10 14:10:36
